#' Generate residual draws from a `brms` model object
#'
#' @param input A dataframe for which to generate model predictions/residuals.
#' @param object A `brms` model object.
#' @param yvar Name of the response variable used to generate residuals.
#' @param ... Arguments passed on to `add_pred_draws_car1()`.
#'
#' @return A dataframe of the type generated by `tidybayes::add_epred_draws()`.
#' @importFrom dplyr %>% ungroup mutate
#' @export
#'
#' @examples
#' library("brms")
#' seed <- 1
#' data <- read.csv(paste0(system.file("extdata", package = "bgamcar1"), "/data.csv"))
#' fit <- fit_stan_model(
#'    paste0(system.file("extdata", package = "bgamcar1"), "/test"),
#'    seed,
#'    bf(y | cens(ycens, y2 = y2) ~ 1),
#'    data,
#'    prior(normal(0, 1), class = Intercept),
#'    car1 = FALSE,
#'    save_warmup = FALSE,
#'    chains = 3
#'  )
#' add_resid_draws_car1(data, fit, yvar = y, car1 = FALSE, draw_ids = 1234)
add_resid_draws_car1 <- function(input, object, yvar, ...) {
  add_pred_draws_car1(input, object, ...) %>%
    ungroup() %>%
    mutate(.residual = {{ yvar }} - .data$.epred)
}
