
#' Add Stan code to the generated quantities block
#'
#' @param scode_raw Stan code generated by `brms::make_stancode()`.
#' @param new_code A character string containing Stan code to add to the generated quantities block
#'
#' @return  A Stan program of class `brmsmodel`.
#' @importFrom stringr str_replace
#' @export
#'
#' @examples
#' library("brms")
#' data <- read.csv(paste0(system.file("extdata", package = "bgamcar1"), "/data_car1.csv"))
#' scode <- make_stancode(bf(y ~ ar(time = x)), data)
#' add_stancode(scode, "\n  // add new code here:")
add_stancode <- function(scode_raw, new_code) {
  scode <- str_replace(
    scode_raw,
    "(generated quantities \\{\n(.|\n)*?)(?=\n\\})",
    paste(c("\\1", new_code), collapse = "")
  )
  class(scode) <- "brmsmodel"
  scode
}
