#' Fit a stan model using (modified) code and data generated by brms
#'
#' @param file Load/save csvs to this filepath and name.
#' @param seed Random seed passed to `rstan::stan()`.
#' @param bform A `brms` formula/
#' @param bdata A data frame used to fit the model.
#' @param bpriors Priors specified by `brms` functions.
#' @param car1 Logical. Generate CAR(1) errors?
#' @param sample_prior Passed on to `brms::brm()`.
#' @param ... Passed on to `rstan::stan()`.
#'
#' @return A `brms` model object fitted with `rstan`.
#' @importFrom stringr str_remove str_extract str_detect
#' @importFrom brms brm rename_pars make_stancode make_standata student
#' @importFrom rstan stan read_stan_csv
#' @importFrom dplyr %>%
#' @export
#'
#' @examples
#' library("brms")
#' seed <- 1
#' data <- read.csv(paste0(system.file("extdata", package = "bgamcar1"), "/data.csv"))
#' fit <- fit_stan_model(
#'    paste0(system.file("extdata", package = "bgamcar1"), "/test"),
#'    seed,
#'    bf(y | cens(ycens, y2 = y2) ~ 1),
#'    data,
#'    prior(normal(0, 1), class = Intercept),
#'    car1 = FALSE,
#'    save_warmup = FALSE,
#'    chains = 3
#'  )
fit_stan_model <- function(file,
                           seed,
                           bform,
                           bdata,
                           bpriors = NULL,
                           car1 = TRUE,
                           sample_prior = "no",
                           ...) {
  path <- str_remove(file, "\\/[^\\/]+$")
  csvfiles <- list.files(path = path, pattern = ".+\\.csv", full.names = TRUE)

  regex <- str_extract(file, "[^\\/]+$") %>%
    paste0("_\\d\\.csv")

  regex <- paste0("/", regex)

  # generate stan data:

  data <- brms::make_standata(
    bform,
    data = bdata,
    prior = bpriors,
    family = student(),
    sample_prior = sample_prior
  )

  if (car1) {
    data$s <- bdata$d_x
  }

  # generate stan code:

  code <- brms::make_stancode(
    bform,
    data = bdata,
    prior = bpriors,
    family = student(),
    sample_prior = sample_prior
  )

  if (car1) {
    code <- modify_stancode(code)
  }

  # fit model:

  csv_matches <- str_detect(csvfiles, regex)

  stanmod <- if (sum(csv_matches) > 0) {
    csvfiles[csv_matches] %>%
      rstan::read_stan_csv()
  } else {
    rstan::stan(
      model_code = code,
      data = data,
      sample_file = file, # output in csv format
      seed = seed,
      ...
    )
  }

  # feed back into brms:

  brmsmod <- brm(
    bform,
    data = bdata,
    prior = bpriors,
    family = student(),
    empty = TRUE
  )
  brmsmod$fit <- stanmod
  brmsmod <- rename_pars(brmsmod)

  return(brmsmod)
}
