#' Modify stan code generated by `brms` to fit a CAR(1) model
#'
#' @description `modify_stancode()` resets the lower bound on the `ar` parameter to zero. It is compatible with priors such as
#' `normal()` (check to make sure it makes the expected modifications before using).
#'
#' @param scode_raw Stan code generated by `brms::make_stancode()`.
#' @param modify Specify which modification to make. The default (and currently the only option) is `"car1"`,
#' which creates the CAR(1) error term.
#'
#' @return A Stan program of class `brmsmodel`.
#' @importFrom stringr str_replace str_remove_all
#' @importFrom dplyr %>%
#' @export
#'
#' @examples
#' seed <- 1
#' library("brms")
#' seed <- 1
#' data <- read.csv(paste0(system.file("extdata", package = "bgamcar1"), "/data.csv"))
#' fit <- fit_stan_model(
#'    paste0(system.file("extdata", package = "bgamcar1"), "/test"),
#'    seed,
#'    bf(y | cens(ycens, y2 = y2) ~ 1),
#'    data,
#'    prior(normal(0, 1), class = Intercept),
#'    car1 = FALSE,
#'    save_warmup = FALSE,
#'    chains = 3
#'  )
#' modify_stancode(fit$model)
modify_stancode <- function(scode_raw, modify = "car1") {
  if (modify == "car1") modify_stancode_car1(scode_raw)
}

modify_stancode_car1 <- function(scode_raw) {
  scode <- scode_raw %>%
    # add time difference variable s:
    str_replace(
      "response variable\\\n",
      "response variable\n  vector[N] s;  // CAR(1) exponent\n"
    ) %>%
    # set lower bound of zero on ar param:
    str_replace(
      "vector\\[Kar\\] ar;",
      "vector<lower=0, upper=1>[Kar] ar;"
    ) %>%
    # convert AR process to CAR1:
    str_replace(
      "mu\\[n\\] \\+= Err\\[n, 1:Kar\\] \\* ar;",
      "mu[n] += Err[n, 1] * pow(ar[1], s[n]); // CAR(1)"
    )

  class(scode) <- "brmsmodel"

  return(scode)
}

modify_stancode_censored <- function(scode, var) {

  var <- str_remove_all(var, "_")

  for(i in seq_len(length(var))) {

    # modifications to data block:
    n_cens <- glue("int<lower=0> Ncens_{var[i]};  // number of left-censored")
    j_cens <- glue("int<lower=1> Jcens_{var[i]}[Ncens_{var[i]}];  // positions of left-censored")
    u <- glue("real U_{var[i]};  // left-censoring limit")
    # modifications to parameters block:
    y_cens <- glue("vector<upper=U_{var[i]}>[Ncens_{var[i]}] Ycens_{var[i]};  // estimated left-censored")
    # modifications to model block:
    yl <- glue("Yl_{var[i]}[Jcens_{var[i]}] = Ycens_{var[i]}; // add imputed left-censored values")

    scode <- scode %>%
      # modifications to data block:
      str_replace(
        "(data \\{\n(.|\n)*?)(?=\n\\})",
        paste(c("\\1", n_cens, j_cens, u), collapse = "\n  ")
      ) %>%
      # modifications to parameters block:
      str_replace(
        "(parameters \\{\n(.|\n)*?)(?=\n\\})",
        paste(c("\\1\n  ", y_cens), collapse = "")
      ) %>%
      # modifications to model block:
      str_replace(
        "(model \\{\n(.|\n)*?)(?=\n    mu_)",
        paste(c("\\1\n    ", yl), collapse = "")
      )

  }

  class(scode) <- "brmsmodel"

  scode

}
