#' Modify stan code generated by `brms` to fit a CAR(1) model
#'
#' @description `modify_stancode()` resets the lower bound on the `ar` parameter to zero. It is compatible with priors such as
#' `normal()` (check to make sure it makes the expected modifications before using).
#'
#' @param scode_raw Stan code generated by `brms::make_stancode()`.
#'
#' @return A Stan program of class `brmsmodel`.
#' @importFrom stringr str_replace
#' @importFrom dplyr %>%
#' @export
#'
#' @examples
#' seed <- 1
#' library("brms")
#' seed <- 1
#' data <- read.csv(paste0(system.file("extdata", package = "bgamcar1"), "/data.csv"))
#' fit <- fit_stan_model(
#'    paste0(system.file("extdata", package = "bgamcar1"), "/test"),
#'    seed,
#'    bf(y | cens(ycens) ~ 1),
#'    data,
#'    prior(normal(0, 1), class = Intercept),
#'    car1 = FALSE,
#'    save_warmup = FALSE,
#'    chains = 3
#'  )
#' modify_stancode(fit$model)
modify_stancode <- function(scode_raw) {
  scode <- scode_raw %>%
    # add time difference variable s:
    str_replace(
      "response variable\\\n",
      "response variable\n  vector[N] s;  // CAR(1) exponent\n"
    ) %>%
    # set lower bound of zero on ar param:
    str_replace(
      "vector\\[Kar\\] ar;",
      "vector<lower=0, upper=1>[Kar] ar;"
    ) %>%
    # convert AR process to CAR1:
    str_replace(
      "mu\\[n\\] \\+= Err\\[n, 1:Kar\\] \\* ar;",
      "mu[n] += Err[n, 1] * pow(ar[1], s[n]); // CAR(1)"
    )

  class(scode) <- "brmsmodel"

  return(scode)
}
